[2022-08-11 06:18:43,496] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V3.load_into_daily_food_availability_table manual__2022-08-11T06:03:05.676328+00:00 [queued]>
[2022-08-11 06:18:43,529] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V3.load_into_daily_food_availability_table manual__2022-08-11T06:03:05.676328+00:00 [queued]>
[2022-08-11 06:18:43,530] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 06:18:43,532] {taskinstance.py:1377} INFO - Starting attempt 4 of 6
[2022-08-11 06:18:43,533] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 06:18:43,578] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): load_into_daily_food_availability_table> on 2022-08-11 06:03:05.676328+00:00
[2022-08-11 06:18:43,602] {standard_task_runner.py:52} INFO - Started process 20278 to run task
[2022-08-11 06:18:43,620] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_V3', 'load_into_daily_food_availability_table', 'manual__2022-08-11T06:03:05.676328+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpzfe4x18e', '--error-file', '/tmp/tmp72ai6xcg']
[2022-08-11 06:18:43,638] {standard_task_runner.py:80} INFO - Job 345: Subtask load_into_daily_food_availability_table
[2022-08-11 06:18:43,876] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_V3.load_into_daily_food_availability_table manual__2022-08-11T06:03:05.676328+00:00 [running]> on host c9fcec21ee59
[2022-08-11 06:18:44,172] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_V3
AIRFLOW_CTX_TASK_ID=load_into_daily_food_availability_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T06:03:05.676328+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T06:03:05.676328+00:00
[2022-08-11 06:18:44,174] {s3_to_snowflake.py:135} INFO - Executing COPY command...
[2022-08-11 06:18:44,226] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-11 06:18:44,269] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-11 06:18:44,275] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-11 06:18:44,276] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-11 06:18:45,628] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-11 06:18:45,916] {cursor.py:739} INFO - query execution done
[2022-08-11 06:18:45,918] {snowflake.py:328} INFO - Running statement: COPY INTO public.daily_food_availability
FROM @s3_stage/
files=('loss-adjusted-food-availability-staged.csv')
file_format=csv_format, parameters: None
[2022-08-11 06:18:45,919] {cursor.py:715} INFO - query: [COPY INTO public.daily_food_availability FROM @s3_stage/ files=('loss-adjusted-f...]
[2022-08-11 06:18:47,342] {cursor.py:739} INFO - query execution done
[2022-08-11 06:18:47,346] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://s3-bucket-staged/loss-adjusted-food-availability-staged.csv', 'status': 'LOADED', 'rows_parsed': 12447, 'rows_loaded': 12447, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-08-11 06:18:47,348] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 06:18:47,352] {snowflake.py:343} INFO - Snowflake query id: 01a635da-0004-2869-001e-00070003427a
[2022-08-11 06:18:47,354] {connection.py:557} INFO - closed
[2022-08-11 06:18:47,525] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-11 06:18:47,737] {s3_to_snowflake.py:137} INFO - COPY command completed
[2022-08-11 06:18:47,902] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_DAG_V3, task_id=load_into_daily_food_availability_table, execution_date=20220811T060305, start_date=20220811T061843, end_date=20220811T061847
[2022-08-11 06:18:48,053] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 06:18:48,288] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
