[2022-08-11 19:26:57,703] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V2.Ingest_from_consumer_price_index manual__2022-08-11T05:57:31.582348+00:00 [queued]>
[2022-08-11 19:26:57,712] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V2.Ingest_from_consumer_price_index manual__2022-08-11T05:57:31.582348+00:00 [queued]>
[2022-08-11 19:26:57,713] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 19:26:57,714] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2022-08-11 19:26:57,715] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 19:26:57,725] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): Ingest_from_consumer_price_index> on 2022-08-11 05:57:31.582348+00:00
[2022-08-11 19:26:57,730] {standard_task_runner.py:52} INFO - Started process 2271 to run task
[2022-08-11 19:26:57,733] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_V2', 'Ingest_from_consumer_price_index', 'manual__2022-08-11T05:57:31.582348+00:00', '--job-id', '487', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp851_j_hl', '--error-file', '/tmp/tmpejhokury']
[2022-08-11 19:26:57,736] {standard_task_runner.py:80} INFO - Job 487: Subtask Ingest_from_consumer_price_index
[2022-08-11 19:26:57,781] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_V2.Ingest_from_consumer_price_index manual__2022-08-11T05:57:31.582348+00:00 [running]> on host ce1be8c59d56
[2022-08-11 19:26:57,831] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_V2
AIRFLOW_CTX_TASK_ID=Ingest_from_consumer_price_index
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T05:57:31.582348+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T05:57:31.582348+00:00
[2022-08-11 19:26:57,868] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest/ingestor.py", line 124, in run
    if usda:
NameError: name 'usda' is not defined
[2022-08-11 19:26:57,877] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_DAG_V2, task_id=Ingest_from_consumer_price_index, execution_date=20220811T055731, start_date=20220811T192657, end_date=20220811T192657
[2022-08-11 19:26:57,885] {standard_task_runner.py:97} ERROR - Failed to execute job 487 for task Ingest_from_consumer_price_index (name 'usda' is not defined; 2271)
[2022-08-11 19:26:57,906] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-11 19:26:57,939] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
