[2022-08-11 05:55:37,453] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V2.load_into_price_index_table manual__2022-08-11T00:39:54.349266+00:00 [queued]>
[2022-08-11 05:55:37,467] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V2.load_into_price_index_table manual__2022-08-11T00:39:54.349266+00:00 [queued]>
[2022-08-11 05:55:37,469] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 05:55:37,471] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-11 05:55:37,472] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 05:55:37,518] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): load_into_price_index_table> on 2022-08-11 00:39:54.349266+00:00
[2022-08-11 05:55:37,527] {standard_task_runner.py:52} INFO - Started process 17958 to run task
[2022-08-11 05:55:37,541] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_V2', 'load_into_price_index_table', 'manual__2022-08-11T00:39:54.349266+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp_mjej4ry', '--error-file', '/tmp/tmpaz4_ztvb']
[2022-08-11 05:55:37,545] {standard_task_runner.py:80} INFO - Job 205: Subtask load_into_price_index_table
[2022-08-11 05:55:37,744] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_V2.load_into_price_index_table manual__2022-08-11T00:39:54.349266+00:00 [running]> on host c9fcec21ee59
[2022-08-11 05:55:37,993] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_V2
AIRFLOW_CTX_TASK_ID=load_into_price_index_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T00:39:54.349266+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T00:39:54.349266+00:00
[2022-08-11 05:55:37,996] {s3_to_snowflake.py:135} INFO - Executing COPY command...
[2022-08-11 05:55:38,019] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-11 05:55:38,027] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-11 05:55:38,037] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-11 05:55:38,039] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-11 05:55:38,933] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-11 05:55:39,116] {cursor.py:739} INFO - query execution done
[2022-08-11 05:55:39,118] {snowflake.py:328} INFO - Running statement: COPY INTO public.price_index
FROM @s3_stage/
files=('price-index-staged.csv')
file_format=csv_format, parameters: None
[2022-08-11 05:55:39,121] {cursor.py:715} INFO - query: [COPY INTO public.price_index FROM @s3_stage/ files=('price-index-staged.csv') fi...]
[2022-08-11 05:55:39,332] {cursor.py:739} INFO - query execution done
[2022-08-11 05:55:39,339] {connection.py:557} INFO - closed
[2022-08-11 05:55:39,512] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-11 05:55:39,680] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/transfers/s3_to_snowflake.py", line 136, in execute
    snowflake_hook.run(copy_query, self.autocommit)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 332, in run
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 804, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 280, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 331, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 217, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01a635c3-0004-286b-001e-0007000312a2: SQL compilation error:
Stage 'US_FOOD_NUTRITION.PUBLIC.S3_STAGE' does not exist or not authorized.
[2022-08-11 05:55:39,691] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_DAG_V2, task_id=load_into_price_index_table, execution_date=20220811T003954, start_date=20220811T055537, end_date=20220811T055539
[2022-08-11 05:55:39,703] {standard_task_runner.py:97} ERROR - Failed to execute job 205 for task load_into_price_index_table (002003 (02000): 01a635c3-0004-286b-001e-0007000312a2: SQL compilation error:
Stage 'US_FOOD_NUTRITION.PUBLIC.S3_STAGE' does not exist or not authorized.; 17958)
[2022-08-11 05:55:39,742] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-11 05:55:39,773] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-11 19:17:02,007] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V2.Load_into_price_index_table manual__2022-08-11T00:39:54.349266+00:00 [queued]>
[2022-08-11 19:17:02,030] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V2.Load_into_price_index_table manual__2022-08-11T00:39:54.349266+00:00 [queued]>
[2022-08-11 19:17:02,032] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 19:17:02,033] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-11 19:17:02,035] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 19:17:02,078] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): Load_into_price_index_table> on 2022-08-11 00:39:54.349266+00:00
[2022-08-11 19:17:02,095] {standard_task_runner.py:52} INFO - Started process 1408 to run task
[2022-08-11 19:17:02,099] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_V2', 'Load_into_price_index_table', 'manual__2022-08-11T00:39:54.349266+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpdoxiy8ag', '--error-file', '/tmp/tmpvwkv1jqc']
[2022-08-11 19:17:02,112] {standard_task_runner.py:80} INFO - Job 440: Subtask Load_into_price_index_table
[2022-08-11 19:17:02,205] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_V2.Load_into_price_index_table manual__2022-08-11T00:39:54.349266+00:00 [running]> on host ce1be8c59d56
[2022-08-11 19:17:02,390] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_V2
AIRFLOW_CTX_TASK_ID=Load_into_price_index_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T00:39:54.349266+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T00:39:54.349266+00:00
[2022-08-11 19:17:02,394] {s3_to_snowflake.py:135} INFO - Executing COPY command...
[2022-08-11 19:17:02,428] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-11 19:17:02,438] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-11 19:17:02,441] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-11 19:17:02,443] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-11 19:17:03,682] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-11 19:17:03,923] {cursor.py:739} INFO - query execution done
[2022-08-11 19:17:03,924] {snowflake.py:328} INFO - Running statement: COPY INTO public.price_index
FROM @s3_stage/
files=('price-index-staged.csv')
file_format=csv_format, parameters: None
[2022-08-11 19:17:03,925] {cursor.py:715} INFO - query: [COPY INTO public.price_index FROM @s3_stage/ files=('price-index-staged.csv') fi...]
[2022-08-11 19:17:04,380] {cursor.py:739} INFO - query execution done
[2022-08-11 19:17:04,382] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://s3-bucket-staged/price-index-staged.csv', 'status': 'LOAD_SKIPPED', 'rows_parsed': 0, 'rows_loaded': 0, 'error_limit': None, 'errors_seen': 1, 'first_error': 'File was loaded before.', 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-08-11 19:17:04,385] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 19:17:04,386] {snowflake.py:343} INFO - Snowflake query id: 01a638e5-0004-2875-001e-0007000353da
[2022-08-11 19:17:04,387] {connection.py:557} INFO - closed
[2022-08-11 19:17:04,536] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-11 19:17:04,746] {s3_to_snowflake.py:137} INFO - COPY command completed
[2022-08-11 19:17:04,777] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_DAG_V2, task_id=Load_into_price_index_table, execution_date=20220811T003954, start_date=20220811T191702, end_date=20220811T191704
[2022-08-11 19:17:04,817] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 19:17:04,857] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
