[2022-08-12 01:30:41,838] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_US_FOOD_NUTRITION.Load_into_food_consumption_estimates_table manual__2022-08-12T01:21:26.402383+00:00 [queued]>
[2022-08-12 01:30:41,866] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_US_FOOD_NUTRITION.Load_into_food_consumption_estimates_table manual__2022-08-12T01:21:26.402383+00:00 [queued]>
[2022-08-12 01:30:41,867] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 01:30:41,868] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-12 01:30:41,870] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 01:30:41,892] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): Load_into_food_consumption_estimates_table> on 2022-08-12 01:21:26.402383+00:00
[2022-08-12 01:30:41,906] {standard_task_runner.py:52} INFO - Started process 957 to run task
[2022-08-12 01:30:41,927] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_US_FOOD_NUTRITION', 'Load_into_food_consumption_estimates_table', 'manual__2022-08-12T01:21:26.402383+00:00', '--job-id', '781', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpmppgss1i', '--error-file', '/tmp/tmpxdpes7r2']
[2022-08-12 01:30:41,952] {standard_task_runner.py:80} INFO - Job 781: Subtask Load_into_food_consumption_estimates_table
[2022-08-12 01:30:42,100] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_US_FOOD_NUTRITION.Load_into_food_consumption_estimates_table manual__2022-08-12T01:21:26.402383+00:00 [running]> on host ae5c2449a624
[2022-08-12 01:30:42,208] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_US_FOOD_NUTRITION
AIRFLOW_CTX_TASK_ID=Load_into_food_consumption_estimates_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T01:21:26.402383+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T01:21:26.402383+00:00
[2022-08-12 01:30:42,210] {s3_to_snowflake.py:135} INFO - Executing COPY command...
[2022-08-12 01:30:42,230] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-12 01:30:42,235] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-12 01:30:42,236] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-12 01:30:42,237] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-12 01:30:43,723] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-12 01:30:43,909] {cursor.py:739} INFO - query execution done
[2022-08-12 01:30:43,914] {snowflake.py:328} INFO - Running statement: COPY INTO public.food_consumption_estimates
FROM @s3_stage/
files=('food-consumption-estimates-staged.csv')
file_format=csv_format, parameters: None
[2022-08-12 01:30:43,917] {cursor.py:715} INFO - query: [COPY INTO public.food_consumption_estimates FROM @s3_stage/ files=('food-consump...]
[2022-08-12 01:30:45,598] {cursor.py:739} INFO - query execution done
[2022-08-12 01:30:45,600] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://s3-bucket-staged/food-consumption-estimates-staged.csv', 'status': 'LOADED', 'rows_parsed': 196, 'rows_loaded': 196, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-08-12 01:30:45,601] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-12 01:30:45,602] {snowflake.py:343} INFO - Snowflake query id: 01a63a5a-0004-2874-001e-000700037286
[2022-08-12 01:30:45,609] {connection.py:557} INFO - closed
[2022-08-12 01:30:45,738] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-12 01:30:46,076] {s3_to_snowflake.py:137} INFO - COPY command completed
[2022-08-12 01:30:46,092] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_DAG_US_FOOD_NUTRITION, task_id=Load_into_food_consumption_estimates_table, execution_date=20220812T012126, start_date=20220812T013041, end_date=20220812T013046
[2022-08-12 01:30:46,139] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 01:30:46,174] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
