[2022-08-12 18:29:36,199] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG.Load_into_food_expenditure_table manual__2022-08-12T18:20:52.559703+00:00 [queued]>
[2022-08-12 18:29:36,220] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG.Load_into_food_expenditure_table manual__2022-08-12T18:20:52.559703+00:00 [queued]>
[2022-08-12 18:29:36,225] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 18:29:36,226] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-12 18:29:36,227] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 18:29:36,242] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): Load_into_food_expenditure_table> on 2022-08-12 18:20:52.559703+00:00
[2022-08-12 18:29:36,257] {standard_task_runner.py:52} INFO - Started process 930 to run task
[2022-08-12 18:29:36,264] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG', 'Load_into_food_expenditure_table', 'manual__2022-08-12T18:20:52.559703+00:00', '--job-id', '919', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp9b7qxxzv', '--error-file', '/tmp/tmpvnn9abwj']
[2022-08-12 18:29:36,272] {standard_task_runner.py:80} INFO - Job 919: Subtask Load_into_food_expenditure_table
[2022-08-12 18:29:36,344] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG.Load_into_food_expenditure_table manual__2022-08-12T18:20:52.559703+00:00 [running]> on host 00aa0783f116
[2022-08-12 18:29:36,418] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG
AIRFLOW_CTX_TASK_ID=Load_into_food_expenditure_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T18:20:52.559703+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T18:20:52.559703+00:00
[2022-08-12 18:29:36,420] {s3_to_snowflake.py:135} INFO - Executing COPY command...
[2022-08-12 18:29:36,431] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-12 18:29:36,435] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-12 18:29:36,440] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-12 18:29:36,441] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-12 18:29:37,288] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-12 18:29:37,527] {cursor.py:739} INFO - query execution done
[2022-08-12 18:29:37,529] {snowflake.py:328} INFO - Running statement: COPY INTO public.food_expenditure
FROM @s3_stage/
files=('food-expenditure-staged.csv')
file_format=csv_format, parameters: None
[2022-08-12 18:29:37,530] {cursor.py:715} INFO - query: [COPY INTO public.food_expenditure FROM @s3_stage/ files=('food-expenditure-stage...]
[2022-08-12 18:29:39,379] {cursor.py:739} INFO - query execution done
[2022-08-12 18:29:39,384] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://s3-bucket-staged/food-expenditure-staged.csv', 'status': 'LOADED', 'rows_parsed': 50, 'rows_loaded': 50, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-08-12 18:29:39,385] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-12 18:29:39,387] {snowflake.py:343} INFO - Snowflake query id: 01a63e55-0004-2898-001e-00070003f04e
[2022-08-12 18:29:39,388] {connection.py:557} INFO - closed
[2022-08-12 18:29:39,539] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-12 18:29:39,715] {s3_to_snowflake.py:137} INFO - COPY command completed
[2022-08-12 18:29:39,727] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_DAG, task_id=Load_into_food_expenditure_table, execution_date=20220812T182052, start_date=20220812T182936, end_date=20220812T182939
[2022-08-12 18:29:39,758] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 18:29:39,815] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
