[2022-08-11 04:54:36,010] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V8.load_into_nutrient_intake_estimates_table manual__2022-08-11T04:54:25.622528+00:00 [queued]>
[2022-08-11 04:54:36,066] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V8.load_into_nutrient_intake_estimates_table manual__2022-08-11T04:54:25.622528+00:00 [queued]>
[2022-08-11 04:54:36,067] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 04:54:36,068] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-11 04:54:36,069] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 04:54:36,095] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): load_into_nutrient_intake_estimates_table> on 2022-08-11 04:54:25.622528+00:00
[2022-08-11 04:54:36,110] {standard_task_runner.py:52} INFO - Started process 13769 to run task
[2022-08-11 04:54:36,125] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_V8', 'load_into_nutrient_intake_estimates_table', 'manual__2022-08-11T04:54:25.622528+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpxqh92r8x', '--error-file', '/tmp/tmpsk7c9r7e']
[2022-08-11 04:54:36,129] {standard_task_runner.py:80} INFO - Job 174: Subtask load_into_nutrient_intake_estimates_table
[2022-08-11 04:54:36,385] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_V8.load_into_nutrient_intake_estimates_table manual__2022-08-11T04:54:25.622528+00:00 [running]> on host c9fcec21ee59
[2022-08-11 04:54:36,576] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_V8
AIRFLOW_CTX_TASK_ID=load_into_nutrient_intake_estimates_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T04:54:25.622528+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T04:54:25.622528+00:00
[2022-08-11 04:54:36,582] {s3_to_snowflake.py:135} INFO - Executing COPY command...
[2022-08-11 04:54:36,621] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-11 04:54:36,636] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-11 04:54:36,641] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-11 04:54:36,646] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-11 04:54:37,765] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-11 04:54:37,955] {cursor.py:739} INFO - query execution done
[2022-08-11 04:54:37,958] {snowflake.py:328} INFO - Running statement: COPY INTO public.nutrient_intake_estimates
FROM @s3_stage/
files=('nutrient-intake-estimates-staged.csv')
file_format=csv_format, parameters: None
[2022-08-11 04:54:37,960] {cursor.py:715} INFO - query: [COPY INTO public.nutrient_intake_estimates FROM @s3_stage/ files=('nutrient-inta...]
[2022-08-11 04:54:39,582] {cursor.py:739} INFO - query execution done
[2022-08-11 04:54:39,585] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://s3-bucket-staged/nutrient-intake-estimates-staged.csv', 'status': 'LOADED', 'rows_parsed': 112, 'rows_loaded': 112, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-08-11 04:54:39,587] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 04:54:39,589] {snowflake.py:343} INFO - Snowflake query id: 01a63586-0004-2870-001e-000700030292
[2022-08-11 04:54:39,591] {connection.py:557} INFO - closed
[2022-08-11 04:54:39,766] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-11 04:54:40,064] {s3_to_snowflake.py:137} INFO - COPY command completed
[2022-08-11 04:54:40,079] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_DAG_V8, task_id=load_into_nutrient_intake_estimates_table, execution_date=20220811T045425, start_date=20220811T045436, end_date=20220811T045440
[2022-08-11 04:54:40,104] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 04:54:40,139] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
