[2022-08-11 01:53:20,750] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V6.load_into_food_availability_calories manual__2022-08-11T01:53:16.706758+00:00 [queued]>
[2022-08-11 01:53:20,783] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ETL_DAG_V6.load_into_food_availability_calories manual__2022-08-11T01:53:16.706758+00:00 [queued]>
[2022-08-11 01:53:20,788] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 01:53:20,789] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-08-11 01:53:20,790] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 01:53:20,817] {taskinstance.py:1397} INFO - Executing <Task(S3ToSnowflakeOperator): load_into_food_availability_calories> on 2022-08-11 01:53:16.706758+00:00
[2022-08-11 01:53:20,826] {standard_task_runner.py:52} INFO - Started process 6415 to run task
[2022-08-11 01:53:20,849] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_DAG_V6', 'load_into_food_availability_calories', 'manual__2022-08-11T01:53:16.706758+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpl1xuez2i', '--error-file', '/tmp/tmphecr3hkd']
[2022-08-11 01:53:20,854] {standard_task_runner.py:80} INFO - Job 159: Subtask load_into_food_availability_calories
[2022-08-11 01:53:20,962] {task_command.py:371} INFO - Running <TaskInstance: ETL_DAG_V6.load_into_food_availability_calories manual__2022-08-11T01:53:16.706758+00:00 [running]> on host c9fcec21ee59
[2022-08-11 01:53:21,019] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=narapady
AIRFLOW_CTX_DAG_ID=ETL_DAG_V6
AIRFLOW_CTX_TASK_ID=load_into_food_availability_calories
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T01:53:16.706758+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T01:53:16.706758+00:00
[2022-08-11 01:53:21,027] {s3_to_snowflake.py:135} INFO - Executing COPY command...
[2022-08-11 01:53:21,044] {base.py:68} INFO - Using connection ID 'snowflake_conn' for task execution.
[2022-08-11 01:53:21,050] {connection.py:275} INFO - Snowflake Connector for Python Version: 2.7.11, Python Version: 3.7.13, Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-11.3
[2022-08-11 01:53:21,060] {connection.py:927} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-11 01:53:21,061] {connection.py:944} INFO - Setting use_openssl_only mode to False
[2022-08-11 01:53:21,965] {cursor.py:715} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-11 01:53:22,159] {cursor.py:739} INFO - query execution done
[2022-08-11 01:53:22,160] {snowflake.py:328} INFO - Running statement: COPY INTO public.food_availability_calories
FROM @s3_stage/
files=('totals-staged.csv')
file_format=csv_format, parameters: None
[2022-08-11 01:53:22,162] {cursor.py:715} INFO - query: [COPY INTO public.food_availability_calories FROM @s3_stage/ files=('totals-stage...]
[2022-08-11 01:53:23,897] {cursor.py:739} INFO - query execution done
[2022-08-11 01:53:23,898] {snowflake.py:338} INFO - Statement execution info - {'file': 's3://s3-bucket-staged/totals-staged.csv', 'status': 'LOADED', 'rows_parsed': 48, 'rows_loaded': 48, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-08-11 01:53:23,899] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 01:53:23,900] {snowflake.py:343} INFO - Snowflake query id: 01a634d1-0004-2868-001e-0007000330ba
[2022-08-11 01:53:23,901] {connection.py:557} INFO - closed
[2022-08-11 01:53:24,032] {connection.py:560} INFO - No async queries seem to be running, deleting session
[2022-08-11 01:53:24,199] {s3_to_snowflake.py:137} INFO - COPY command completed
[2022-08-11 01:53:24,233] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ETL_DAG_V6, task_id=load_into_food_availability_calories, execution_date=20220811T015316, start_date=20220811T015320, end_date=20220811T015324
[2022-08-11 01:53:24,290] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 01:53:24,333] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
